[window]
decorations = "Full"
opacity = 0.65
blur = true
dynamic_title = true

[font]
normal = { family = "MesloLGL Nerd Font", style = "Regular" }
bold = { family = "MesloLGL Nerd Font", style = "Bold" }
italic = { family = "MesloLGL Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGL Nerd Font", style = "Bold Italic" }
size = 14.0

[selection]
save_to_clipboard = false

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_timeout = 0

[mouse]
hide_when_typing = true

[general]
import = ["~/.config/alacritty/themes/github_dark_tritanopia.toml"]
