[window]
decorations = "Full"
opacity = 0.50
blur = true
dynamic_title = false

[font]
normal = { family = "MesloLGL Nerd Font", style = "Regular" }
bold = { family = "MesloLGL Nerd Font", style = "Bold" }
italic = { family = "MesloLGL Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGL Nerd Font", style = "Bold Italic" }

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_timeout = 0

[mouse]
hide_when_typing = true
