theme = "dracula_at_night"

[editor]
cursorline = true
bufferline = "multiple"
popup-border = "all"
color-modes = true
line-number = "relative"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace.render]
tab = "all"
space = "none"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1


[editor.soft-wrap]
enable = true
max-wrap = 15
max-indent-retain = 0

[keys.normal]
# Maps Ctrl-s to the :write (save file)
C-s = ":w"
C-g = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload-all",
]

[keys.insert]
# Maps Alt-X to enter normal mode
"A-x" = "normal_mode"

# Maps `jk` to exit insert mode
j = { k = "normal_mode" }
